#Configuracion de conexion a MongoDB
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=${MONGO_DATABASE}
spring.data.mongodb.username=${MONGO_USERNAME}
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.authentication-database=admin
# Mostrar los queries en la consola (util para debug en btg_test)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
